export default {
  title: "light",
  colors: {
    background: "#F0F0F7",
    primaryLighter: "#9871F5",
    primaryLight: "#916BEA",
    primary: "#8257E5",
    primaryDarker: "#6842C2",
    secondary: "#04D361",
    secondaryDark: "#04BF58",
    titleInPrimary: "#FFF",
    textInPrimary: "#D4C2FF",
    textTitle: "#32264D",
    textComplement: "#9C98A6",
    textBase: "#6A6180",
    lineInWhite: "#FFF",
    inputBackground: "#F8F8FC",
    buttonText: "#FFF",
    boxBase: "#FFF",
    boxFooter: "#FAFAFC",
  },
  fontSizes: {
    default: "1.4rem",
    large: "1.6rem",
    small: "1.2rem",
    tiny: "1rem",
  },
  spacing: {
    default: "1.6rem",
    vertical: "1.6rem 0",
    horizontal: "0 1.6rem",
    large: "2.4rem",
  },
  transition: {
    defaut: "180ms ease-in-out",
  },
};
